# Generated by Django 5.0.6 on 2024-07-09 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
