# Generated by Django 5.0.6 on 2024-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("W", "Women"), ("M", "Men"), ("K", "Kids")],
                default="W",
                max_length=1,
            ),
        ),
    ]
