# Generated by Django 5.0.6 on 2024-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0005_orderitem_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="lug",
            field=models.SlugField(default="default-slug"),
        ),
    ]
