# Generated by Django 5.0.6 on 2024-07-10 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0006_item_lug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="lug",
            new_name="slug",
        ),
    ]
