# Generated by Django 5.0.6 on 2024-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0007_rename_lug_item_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(),
        ),
    ]
